

let numbers = [
    "Asking for help is a sign of self-respect and self-awareness",
    "Today is a new opportunity to make a positive impact",
    "I am grateful for this life",
    "I am confident and believe in myself",
    "Even when it doesn't feel like it, there is good in the world worth noticing",
    "I allow myself to feel good",
    "I am kind and compassionate toward others",
    "I am kind and compassionate toward myself",
    "I consent to receiving emails and personalized ads",
    "I have what I need to take on the day",
    "I spread light wherever I go",
    "I am capable of balance",
    "I am grateful for all the love and support I experience",
    "I alone am enough",
    "I am appreciated and valued exactly as I am",
    "I am optimistic and always look for the bright side",
    "I am determined and ambitious about what matters most to me",
    "I deserve to be treated with kindness",
    "I am in charge of myself",
    "I am open to all the opportunities life brings my way",
    "I am creative and bring new ideas to the table",
    "I am a problem solver and find solutions to challenges",
    "I am a positive force in the world",
    "I belong here",
    "There is room in my life for joy and abundance",
    "I am grounded and steady, no matter what life throws my way",
    "I am loved and appreciated by those who matter most",
    "I am adventurous and seek out new experiences",
    "I release what no longer serves me",
    "I am honest and authentic",
    "I am unafraid to ask for what I need",
    "My feelings are allowed to be felt",
    "I can let my feelings leave through the same door they entered",
    "I welcome rest and stillness",
    "I have grace and compassion for my mistakes",
    "I deserve freedom and peace",
    "I am brave even when I feel fear",
    "I seek beauty in all things",
    "I am capable of experiencing a wide range of emotions at once",
    "There is nuance in all experiences",
    "I am my own home",
    "I am safe and grounded in my reality",
    "Every action I take has a positive impact on the world",
    "I can spur a ripple of positive change",
    "I have the power to make a difference in someone’s life",
    "I joyfully learn more about what I don’t know",
    "I am a responsible and conscious member of a collective",
    "I choose to live sustainably and protect the environment",
    "I am a source of inspiration and encouragement",
    "I am a strong advocate for justice and equality",
    "I am a leader in my community",
    "I am constantly learning, unlearning, and growing",
    "I choose to put the needs of the collective community above my own",
    "I am kind and compassionate towards all beings",
    "I am committed to making the world a more peaceful place",
    "I am a responsible and trustworthy global citizen",
    "I am a champion of diversity and embrace differences",
    "I make space for all",
    "I am dedicated to leaving the world a better place than I found it",
    "I am proactive in addressing the challenges facing the world",
    "I take action to help others",
    "I always look for the helpers",
    "I am a helper",
    "I am a positive force for good in the world",
    "Even in challenging times, I trust that everything will be okay",
    "I seek out good news in the world and share it with others",
    "I am generous with my time and resources and help those in need",
    "I am committed to creating a world where everyone can thrive",
    "I am an optimist and believe in a bright future for all",
    "I am grateful for the opportunity to make the world a better place",
    "I am humble and always willing to learn and grow",
    "I am confident in my ability to create positive change",
    "I am proud of my contributions to the world",
    "I have what I need to take on the day",
    "I embrace all the possibilities today brings",
    "I am grateful for a new day",
    "I believe in myself",
    "I know there is good in every situation",
    "I see the goodness in others and myself",
    "I am filled with hope and optimism",
    "My confidence is contagious",
    "I am filled with gratitude and surrounded by love",
    "I am always open to learning something new",
    "I have nothing to prove",
    "I am prepared for anything today brings",
    "My ideas and perspectives are valuable",
    "My creativity flows",
    "I make the world a better place",
    "I am overjoyed to live this specific life",
    "I am more than my circumstances",
    "I am a shining light",
    "I am ready for all the amazing things this day has in store for me",
    "I am driven and determined",
    "I contain bottomless wells of ambition and perseverance",
    "Every day, I am growing",
    "I am unstoppable",
    "I embrace challenges as opportunities for growth",
    "I attract positive energy, opportunities, and abundance",
    "I am fearless in the face of obstacles and setbacks",
    "My passion fuels my progress",
    "I am in control of my future",
    "I believe in my ability to make a difference",
    "I am resilient and bounce back from adversity",
    "I am disciplined and committed to my vision",
    "I am focused on the journey, not just the destination",
    "I have the power to change my life",
    "I am confident in my decisions",
    "I trust my intuition",
    "I celebrate my achievements",
    "I am allowed to take breaks",
    "Rest is required to achieve growth",
    "I am persistent",
    "My positive attitude attracts success",
    "I am grateful for all the opportunities that come my way",
    "I am constantly learning and growing",
    "I have the courage to take risks",
    "I am dedicated to making the most of every moment",
    "I am my own biggest fan",
    "I am committed to living a life of purpose",
    "I prioritize my well-being and make time for self-care",
    "I deserve to feel happy, healthy, and nourished",
    "I listen to my body and give it the care it needs",
    "My mental health is just as important as my physical health",
    "I am still worthy of love and respect, even when I don’t feel well",
    "I deserve accommodations and support in all areas of my life",
    "I am worthy of love, kindness, and compassion from myself and others",
    "I am allowed to set boundaries and protect my energy",
    "I am allowed to center pleasure; I deserve to feel good",
    "I make time for activities that bring me joy and relaxation",
    "I am gentle with myself and embrace self-compassion",
    "I allow myself to feel my feelings without judgment",
    "My self-care routine is a form of self-love and self-respect",
    "My self-care is allowed to evolve with me",
    "I am mindful of my needs and address them accordingly",
    "It’s admirable to ask for help",
    "When I take care of myself, I give others permission to do the same",
    "The way I love myself shows others how I want to be loved",
    "I take care of myself today so that I can continue to grow and thrive",
    "I nurture my mind, body, and soul with love and care",
    "I am allowed to take up space",
    "I love and appreciate myself more each day",
    "I give myself permission to rest and recharge",
    "I trust my intuition and make decisions that support my well-being",
    "I am committed to making choices that benefit my overall health",
    "My self-worth is not dependent on external factors or achievements",
    "I accept and love myself unconditionally, just as I am",
    "I celebrate my progress, no matter how small it may seem",
    "I am grateful for the opportunity to care for myself and grow",
    "I have control of my thoughts and emotions",
    "I am safe, grounded, and present in my reality",
    "Even when it doesn’t feel like it, I know everything is going to be okay",
    "I acknowledge my anxiety, but I don’t let it define me",
    "I am strong and resilient in the face of challenges",
    "I choose to be here now",
    "My inner peace is my priority, and I protect it fiercely",
    "I am capable of handling any situation with grace and compassion",
    "I am surrounded by love and support, and I am not alone",
    "I trust in my ability to face and overcome my fears",
    "I am deserving of a calm and peaceful mind",
    "I choose to release worry and stress",
    "Even when my anxiety is trying to protect me, I know best",
    "I have the tools I need to feel grounded and calm",
    "I am grateful for moments of peace and tranquility",
    "My breath is my anchor, grounding me in times of distress",
    "I allow myself to feel my emotions without judgment",
    "I release the need to control every aspect of my life and trust the process",
    "I am a powerful force of light and love, capable of overcoming obstacles",
    "I give myself permission to be gentle with myself",
    "I have the strength to face my anxiety",
    "My confidence grows as I conquer my fears",
    "Inhale anxiety, exhale poetry",
    "I am patient with my progress",
    "Healing is not linear",
    "I give myself permission to care for and prioritize my mental health",
    "I promise to celebrate the little victories",
    "I am continually working towards a more peaceful and balanced life",
    "I am enough",
    "I choose happiness",
    "I am strong and capable",
    "I attract positivity",
    "I am worthy of success",
    "I embrace change",
    "I am confident",
    "I am loved and supported",
    "I trust the journey",
    "I am grateful for today",
    "I am resilient",
    "I believe in myself",
    "I am my own inspiration",
    "I spread kindness",
    "I am present and mindful",
    "I am in control of my destiny",
    "I am a problem solver",
    "I am at peace with myself",
    "I am courageous",
    "I am deserving of abundance",
    "I am creative and resourceful",
    "I am growing every day",
    "I am a positive force",
    "I am a beacon of light",
    "I am unstoppable",
    "I am confident in my abilities and skills",
    "I believe in myself and my potential",
    "I am worthy of success and happiness",
    "I get to define what success looks like",
    "I embrace my unique qualities and strengths",
    "I am deserving of love, respect, and admiration",
    "I am capable of achieving my dreams",
    "I am a powerful force",
    "I am bold in the face of challenges",
    "My confidence grows with every step I take",
    "I have nothing to be ashamed of",
    "I celebrate my accomplishments and learn from my failures",
    "I stand by my decisions and trust the intuition that leads me to them",
    "I stand up for what I believe in",
    "I am comfortable in my own skin and love myself unconditionally",
    "I feel at home in my body",
    "I can always depend on myself",
    "My growth and success are meaningful, but I do not need to achieve anything to be loved",
    "I am proud of who I am and who I am becoming",
    "I surround myself with people who uplift and encourage me",
    "I am in awe of my strengths and achievements",
    "I belong here, and nobody can make me feel like I don’t",
    "I am not defined by my mistakes but by my perseverance",
    "I am flexible and open to changes",
    "I radiate confidence and positive energy",
    "I am the architect of my own life",
    "I am deserving of all the good that comes my way",
    "I am loved",
    "I treat myself and others with kindness",
    "I can do anything I set my mind to",
    "I am a great friend and teammate",
    "I am smart and capable",
    "I am unique and special",
    "I believe in myself",
    "I am a good listener and learner",
    "I am creative and imaginative",
    "I am brave and courageous",
    "I can solve big problems",
    "I am proud of myself",
    "I am responsible and make good choices",
    "I am a helpful and considerate person",
    "My friends and family love me so much",
    "Anything I can imagine is possible",
    "I am honest and trustworthy",
    "I am patient and understanding",
    "I am a good communicator and share my feelings",
    "I am deserving of happiness and success",
    "I am confident in my abilities and skills",
    "I am surrounded by people who care about me",
    "I am a valuable and important person",
    "My feelings matter",
    "I am a continuous learner and embrace new experiences",
    "I am capable of adapting and thriving in any situation",
    "I attract abundance and prosperity",
    "I am a beacon of hope and positivity for those around me",
    "I choose to forgive myself and others",
    "I release negativity",
    "I am a powerful force for change, impacting the world in a positive way",
    "I am compassionate, empathetic, and understanding towards all living beings",
    "I am in control of my thoughts, emotions, and reactions",
    "I am a magnet for success, attracting opportunities and growth",
    "I am capable of overcoming any obstacle or challenge that comes my way",
    "I am surrounded by love, light, and positivity",
    "I honor my body, mind, and spirit, nurturing my well-being",
    "I choose to live with gratitude and appreciation for all that I have",
    "I am a loving and supportive friend, always there for those in need",
    "I am a catalyst for positive change",
    "I am confident in my decisions and trust in the wisdom of the universe",
    "I am committed to living authentically and being true to myself",
    "I am a powerful creator, manifesting my dreams and desires",
    "I am deserving of all the love, happiness, and success that life has to offer",
    "I embrace each new day with enthusiasm, curiosity, and a sense of adventure",
    "I am connected to the beauty and wonder of the natural world",
    "I am a shining example of love, kindness, and compassion in action",
    "I am a force for good, using my talents and abilities to make a difference",
    "I am grounded, centered, and at peace with myself and the world",
    "I am grateful for the endless possibilities that life has to offer, and I embrace them with open arms"


]
